/* DDL CREATE TABLE 文字列のみのテーブル
   DML INSERT データを登録
	文字列に不等号を使う場合 */

-- DDL: CREATE TABLE
CREATE TABLE Chars
(chr CHAR(3) NOT NULL,
PRIMARY KEY(chr));

-- DML: INSERT INTO Char VALUES();

BEGIN TRANSACTION;

INSERT INTO Chars VALUES('1');
INSERT INTO Chars VALUES('2');
INSERT INTO Chars VALUES('3');
INSERT INTO Chars VALUES('10');
INSERT INTO Chars VALUES('11');
INSERT INTO Chars VALUES('222');

COMMIT;